# -*- mode: ruby -*-
# vi: set ft=ruby :

# Solución Ejercicio 2: VM con CentOS Stream 8

Vagrant.configure("2") do |config|

  # Box de CentOS Stream 8
  config.vm.box = "centos/stream8"

  # Hostname personalizado
  config.vm.hostname = "centos-desarrollo"

  # Configuración del provider (VirtualBox)
  config.vm.provider "virtualbox" do |vb|
    # Nombre que aparecerá en VirtualBox
    vb.name = "CentOS-Dev-VM"

    # 2 GB de RAM
    vb.memory = "2048"

    # 2 CPUs
    vb.cpus = 2
  end

end
